/**
 * DATA MOCK — hanya dipakai oleh mock API bawaan (app/api/**) untuk mode demo,
 * yaitu ketika NEXT_PUBLIC_API_URL diset string kosong di .env.local.
 *
 * Ketika NEXT_PUBLIC_API_URL menunjuk ke backend asli (mis. http://localhost:8000),
 * file ini TIDAK PERNAH tersentuh — frontend tetap 100% mengambil data dari API.
 *
 * Deadline dibuat dinamis (relatif terhadap hari ini) agar demo countdown
 * selalu hidup: beberapa lot urgent (<3 hari), beberapa normal, beberapa lewat.
 */
import type { Lot } from "@/types/lot";

/** Tanggal ISO "YYYY-MM-DD" sekarang + n hari. null -> string kosong (tanpa deadline). */
function deadlineIn(days: number | null): string {
  if (days === null) return "";
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/** JSON string array URL foto (meniru format backend: field `foto` adalah string). */
function fotoSet(seed: string, n: number): string {
  if (n <= 0) return "[]";
  const urls = Array.from(
    { length: n },
    (_, i) => `https://picsum.photos/seed/lelanghub-${seed}-${i + 1}/800/600`
  );
  return JSON.stringify(urls);
}

/**
 * Daftar lot contoh yang beragam:
 * - Mencakup semua tier S/A/B/C/D + tier null (belum dinilai).
 * - harga_pasaran & diskon_persen null pada sebagian lot.
 * - kpknl kosong untuk non-DJKN (IBID/KOELAK).
 * - Sebagian foto "[]", sebagian multi-foto, sebagian deadline "".
 */
export const SAMPLE_LOTS: Lot[] = [
  {
    id: "djkn-abc123",
    nama: "1 Unit Laptop Dell Vostro 3470",
    kategori: "Elektronik",
    harga_lelang: 2500000,
    harga_pasaran: 5000000,
    diskon_persen: 50.0,
    tier: "A",
    lokasi: "Semarang",
    kpknl: "KPKNL Semarang",
    deadline: deadlineIn(5),
    link: "https://lelang.go.id/lot-lelang/djkn-abc123",
    foto: fotoSet("abc123", 3),
    sumber: "DJKN",
    uang_jaminan: 500000,
    deskripsi:
      "Laptop Dell Vostro 3470 bekas kondisi masih baik, spesifikasi Intel Core i5-8250U, RAM 8GB, storage 256GB SSD, layar 14 inci HD. Unit telah melalui proses penghapusan aset negara dan dijual dalam kondisi seperti terlihat pada foto. Pembeli wajib melakukan survei terlebih dahulu sebelum mengikuti lelang.",
  },
  {
    id: "djkn-def456",
    nama: "Toyota Avanza 1.5 G Tahun 2019 Bensin M/T",
    kategori: "Kendaraan",
    harga_lelang: 95000000,
    harga_pasaran: 158000000,
    diskon_persen: 39.9,
    tier: "B",
    lokasi: "Jakarta Pusat",
    kpknl: "KPKNL Jakarta",
    deadline: deadlineIn(2),
    link: "https://lelang.go.id/lot-lelang/djkn-def456",
    foto: fotoSet("def456", 4),
    sumber: "DJKN",
    uang_jaminan: 19000000,
    deskripsi:
      "Satu unit mobil dinas Toyota Avanza 1.5 G tahun 2019, transmisi manual, bensin, odometer 78.000 km. STNK dan BPKB lengkap atas nama instansi, siap balik nama. Kondisi mesin normal, interior terawat, terdapat bekas minor pada bumper depan.",
  },
  {
    id: "ibid-771",
    nama: "iPhone 13 128GB Second Kondisi 95%",
    kategori: "Elektronik",
    harga_lelang: 4200000,
    harga_pasaran: 7500000,
    diskon_persen: 44.0,
    tier: "B",
    lokasi: "Jakarta Selatan",
    kpknl: "",
    deadline: deadlineIn(1),
    link: "https://www.ibid.astra.id/lot/ibid-771",
    foto: fotoSet("ibid771", 3),
    sumber: "IBID",
    uang_jaminan: 840000,
    deskripsi:
      "iPhone 13 128GB warna Midnight, kondisi 95% mulus, battery health 89%. Sudah buka FG dan siap pakai, kelengkapan berupa unit dan kabel data saja. Barang dilelang oleh pemilik sebelumnya melalui jalur lelang IBID BFI Finance.",
  },
  {
    id: "djkn-ghi789",
    nama: "Rumah Tapak 2 Lantai LT 180m2 LB 220m2 di Bandung",
    kategori: "Properti",
    harga_lelang: 850000000,
    harga_pasaran: 2400000000,
    diskon_persen: 64.6,
    tier: "A",
    lokasi: "Bandung",
    kpknl: "KPKNL Bandung",
    deadline: deadlineIn(12),
    link: "https://lelang.go.id/lot-lelang/djkn-ghi789",
    foto: fotoSet("ghi789", 5),
    sumber: "DJKN",
    uang_jaminan: 170000000,
    deskripsi:
      "Rumah tapak dua lantai eks aset perumahan negara di kawasan strategis Bandung. Tipe LT 180 m2, LB 220 m2, terdiri dari 4 kamar tidur, 3 kamar mandi, carport 2 mobil. SHM atas nama badan hukum, bertempat bagus dekat pusat kota dan fasilitas umum.",
  },
  {
    id: "koelak-001",
    nama: "1 Lot Perabot Kantor (5 Set Meja + Kursi Kerja)",
    kategori: "Furnitur",
    harga_lelang: 3750000,
    harga_pasaran: null,
    diskon_persen: null,
    tier: null,
    lokasi: "Jakarta Barat",
    kpknl: "",
    deadline: deadlineIn(7),
    link: "https://lelang.beacukai.go.id/lot/koelak-001",
    foto: "[]",
    sumber: "KOELAK",
    uang_jaminan: null,
    deskripsi:
      "Satu lot berisi 5 set meja kerja beserta kursi ergonomis bekas operasional kantor. Barang dijual rak tanpa garansi dalam kondisi seperti terlihat. Harga pasaran belum dinilai oleh tim, mengikuti proses penilaian aset selanjutnya.",
  },
  {
    id: "djkn-jkl012",
    nama: "Tanah Kosong 250 m2 SHM di Kawasan Bekasi Timur",
    kategori: "Properti",
    harga_lelang: 320000000,
    harga_pasaran: 450000000,
    diskon_persen: 28.9,
    tier: "C",
    lokasi: "Bekasi",
    kpknl: "KPKNL Bekasi",
    deadline: deadlineIn(9),
    link: "https://lelang.go.id/lot-lelang/djkn-jkl012",
    foto: fotoSet("jkl012", 2),
    sumber: "DJKN",
    uang_jaminan: 64000000,
    deskripsi:
      "Kavling tanah kosong luas 250 m2 dengan status SHM, lebar muka 8 meter, kontur datar dan siap bangun. Lokasi 5 menit dari akses tol dan pusat perbelanjaan. Cocok untuk investasi maupun pembangunan hunian.",
  },
  {
    id: "ibid-772",
    nama: "Sepeda Gunung Polygon Xtrada 6 Size M",
    kategori: "Olahraga",
    harga_lelang: 1850000,
    harga_pasaran: 2900000,
    diskon_persen: 36.2,
    tier: "B",
    lokasi: "Surabaya",
    kpknl: "",
    deadline: deadlineIn(3),
    link: "https://www.ibid.astra.id/lot/ibid-772",
    foto: fotoSet("ibid772", 2),
    sumber: "IBID",
    uang_jaminan: 370000,
    deskripsi:
      "Sepeda gunung hardtail Polygon Xtrada 6 ukuran frame M, grupset Deore 1x11 speed, rem hidraulik. Kondisi second mantap, baru ganti rantai dan kaset. Dilelang karena proses sewa pembiayaan yang gagal lelang.",
  },
  {
    id: "djkn-mno345",
    nama: "MacBook Pro 14 inci M1 Pro 2021 16GB/512GB",
    kategori: "Elektronik",
    harga_lelang: 12500000,
    harga_pasaran: 24000000,
    diskon_persen: 47.9,
    tier: "B",
    lokasi: "Jakarta Selatan",
    kpknl: "KPKNL Jakarta",
    deadline: deadlineIn(4),
    link: "https://lelang.go.id/lot-lelang/djkn-mno345",
    foto: fotoSet("mno345", 4),
    sumber: "DJKN",
    uang_jaminan: 2500000,
    deskripsi:
      "MacBook Pro 14 inci M1 Pro 2021 warna Silver, RAM 16GB, SSD 512GB, cycle count rendah 112. Kelengkapan unit plus charger original 67W. Kondisi fisik 97% mulus, baterai health 94%, layar bezel mini-LED nyaman untuk kerja profesional.",
  },
  {
    id: "ibid-773",
    nama: "Smart TV LED LG 43 inch UHD 4K",
    kategori: "Elektronik",
    harga_lelang: 2100000,
    harga_pasaran: 5200000,
    diskon_persen: 59.6,
    tier: "A",
    lokasi: "Medan",
    kpknl: "",
    deadline: deadlineIn(1),
    link: "https://www.ibid.astra.id/lot/ibid-773",
    foto: fotoSet("ibid773", 2),
    sumber: "IBID",
    uang_jaminan: 420000,
    deskripsi:
      "Smart TV LG 43 inch UHD 4K webOS, kondisi menyala normal semua fungsi jalan, terdapat baret tipis di bezel bawah. Termasuk remote original. Barang hasil repossess dengan harga jauh di bawah harga pasaran.",
  },
  {
    id: "djkn-pqr678",
    nama: "1 Unit Honda Vario 125 CBS Tahun 2020",
    kategori: "Kendaraan",
    harga_lelang: 14500000,
    harga_pasaran: 21500000,
    diskon_persen: 32.6,
    tier: "B",
    lokasi: "Yogyakarta",
    kpknl: "KPKNL Yogyakarta",
    deadline: deadlineIn(6),
    link: "https://lelang.go.id/lot-lelang/djkn-pqr678",
    foto: fotoSet("pqr678", 3),
    sumber: "DJKN",
    uang_jaminan: 2900000,
    deskripsi:
      "Sepeda motor Honda Vario 125 CBS 2020 biru, odometer 23.400 km, mesin sehat dan dokumen lengkap. Unit eks armada dinas perawatan rutin di AHASS. Siap pakai tanpa perbaikan, cocok untuk harian.",
  },
  {
    id: "koelak-002",
    nama: "2 Unit Mesin Jahit Industrial Single Needle",
    kategori: "Lainnya",
    harga_lelang: 4000000,
    harga_pasaran: 4350000,
    diskon_persen: 8.0,
    tier: "D",
    lokasi: "Semarang",
    kpknl: "",
    deadline: deadlineIn(8),
    link: "https://lelang.beacukai.go.id/lot/koelak-002",
    foto: fotoSet("koelak002", 2),
    sumber: "KOELAK",
    uang_jaminan: null,
    deskripsi:
      "Dua unit mesin jahit industrial single needle merek Brother bekas pabrik garmen. Kondisi mekanik normal namun tampilan berkarat di beberapa bagian logam. Diskon tipis terhadap harga pasaran, disarankan survei sebelum menawar.",
  },
  {
    id: "djkn-stu901",
    nama: "Servis 2 Unit Printer Laserjet Monokrom",
    kategori: "Elektronik",
    harga_lelang: 800000,
    harga_pasaran: 1000000,
    diskon_persen: 20.0,
    tier: "C",
    lokasi: "Jakarta Pusat",
    kpknl: "KPKNL Jakarta",
    deadline: deadlineIn(2),
    link: "https://lelang.go.id/lot-lelang/djkn-stu901",
    foto: "[]",
    sumber: "DJKN",
    uang_jaminan: 160000,
    deskripsi:
      "Dua unit printer laserjet monokrom A4 untuk kantor, kondisi fungsi cetak normal, toner belum termasuk. Cocok sebagai unit cadangan operasional. Diskon tipis, barang diambil apa adanya di gudang KPKNL.",
  },
  {
    id: "ibid-774",
    nama: "Tas Selempang Kulit Premium Authentic Grade A",
    kategori: "Fashion",
    harga_lelang: 8500000,
    harga_pasaran: 22000000,
    diskon_persen: 61.4,
    tier: "A",
    lokasi: "Jakarta Selatan",
    kpknl: "",
    deadline: deadlineIn(10),
    link: "https://www.ibid.astra.id/lot/ibid-774",
    foto: fotoSet("ibid774", 3),
    sumber: "IBID",
    uang_jaminan: 1700000,
    deskripsi:
      "Tas selempang kulit asli grade A dengan hardware gold, sudah diverifikasi oleh tim penilai lelang. Termasuk dust bag dan kartu authentic. Kondisi 90% mulus tanpa defect berarti, penyimpanan yang baik membuat kulit tetap terawat.",
  },
  {
    id: "djkn-vwx234",
    nama: "Tanah dan Bangunan Ruko 3 Lantai di Koridor Bisnis Surabaya",
    kategori: "Properti",
    harga_lelang: 1950000000,
    harga_pasaran: 6500000000,
    diskon_persen: 70.0,
    tier: "S",
    lokasi: "Surabaya",
    kpknl: "KPKNL Surabaya",
    deadline: deadlineIn(15),
    link: "https://lelang.go.id/lot-lelang/djkn-vwx234",
    foto: fotoSet("vwx234", 6),
    sumber: "DJKN",
    uang_jaminan: 390000000,
    deskripsi:
      "SUPER DEAL: ruko 3 lantai LT 95 m2 dengan total bangunan 285 m2 di koridor bisnis ramai Surabaya. Zona komersial,cocok usaha retail, kantor, maupun usaha kuliner. SHM bersertifikat, harga jauh di bawah nilai pasar karena proses eksekusi lelang negara. Kunjungan gudang bisa dijadwalkan dengan petugas.",
  },
  {
    id: "koelak-003",
    nama: "1 Unit Gudang Ring Stainless Steel 6x12 Meter",
    kategori: "Lainnya",
    harga_lelang: 45000000,
    harga_pasaran: 50000000,
    diskon_persen: 10.0,
    tier: "C",
    lokasi: "Jakarta Utara",
    kpknl: "",
    deadline: deadlineIn(11),
    link: "https://lelang.beacukai.go.id/lot/koelak-003",
    foto: fotoSet("koelak003", 2),
    sumber: "KOELAK",
    uang_jaminan: 9000000,
    deskripsi:
      "Struktur gudang ring stainless steel ukuran 6x12 meter bekas fasilitas pabean, pembongkaran dilakukan oleh pemenang lelang. Material tebal masih kokoh, cocok untuk gudang penyimpanan atau carport industri.",
  },
  {
    id: "ibid-775",
    nama: "Jam Tangan Automatic Seiko Presage Sarb033",
    kategori: "Fashion",
    harga_lelang: 1950000,
    harga_pasaran: 3400000,
    diskon_persen: 42.6,
    tier: "B",
    lokasi: "Bandung",
    kpknl: "",
    deadline: deadlineIn(3),
    link: "https://www.ibid.astra.id/lot/ibid-775",
    foto: fotoSet("ibid775", 3),
    sumber: "IBID",
    uang_jaminan: 390000,
    deskripsi:
      "Jam tangan Seiko Presage SARB033 automatic 6R15, dial hitam sunburst dengan case stainless 38mm. Movement sehat, akurasi +8 detik per hari, crystal clear tanpa gores. Tanpa box dan paper, unit saja.",
  },
  {
    id: "djkn-yza567",
    nama: "Sofa Kulit Minimalis 3 Seater + Meja Kopi",
    kategori: "Furnitur",
    harga_lelang: 3200000,
    harga_pasaran: 9500000,
    diskon_persen: 66.3,
    tier: "A",
    lokasi: "Depok",
    kpknl: "KPKNL Depok",
    deadline: deadlineIn(5),
    link: "https://lelang.go.id/lot-lelang/djkn-yza567",
    foto: fotoSet("yza567", 4),
    sumber: "DJKN",
    uang_jaminan: 640000,
    deskripsi:
      "Set sofa kulit sintetis minimalis 3 seater berwarna cokelat tua plus meja kopi kayu jati solid. Bekas ruang tunggu instansi, kondisi struktur kuat, kulit mulus tanpa sobek. Wajib pickup sendiri di gudang Depok.",
  },
  {
    id: "djkn-bcd890",
    nama: "PlayStation 5 Slim Disc Edition + 2 Controller",
    kategori: "Elektronik",
    harga_lelang: 5750000,
    harga_pasaran: 8999000,
    diskon_persen: 36.1,
    tier: "B",
    lokasi: "Jakarta Timur",
    kpknl: "KPKNL Jakarta",
    deadline: deadlineIn(1),
    link: "https://lelang.go.id/lot-lelang/djkn-bcd890",
    foto: fotoSet("bcd890", 3),
    sumber: "DJKN",
    uang_jaminan: 1150000,
    deskripsi:
      "PS5 Slim Disc Edition second dengan 2 unit DualSense controller, garansi resmi masih berjalan sampai bulan depan. Kelengkapan unit, HDMI, 2 controller, dan base stand. Semua fungsi normal, kondisi 96% mulus.",
  },
  {
    id: "ibid-776",
    nama: "Daihatsu Gran Max Pickup 1.5 Tahun 2018",
    kategori: "Kendaraan",
    harga_lelang: 68000000,
    harga_pasaran: 112000000,
    diskon_persen: 39.3,
    tier: "B",
    lokasi: "Semarang",
    kpknl: "",
    deadline: deadlineIn(13),
    link: "https://www.ibid.astra.id/lot/ibid-776",
    foto: fotoSet("ibid776", 4),
    sumber: "IBID",
    uang_jaminan: 13600000,
    deskripsi:
      "Pick up Daihatsu Gran Max 1.5 2018 bak kayu, mesin standar gak bapuk, dokumen lengkap dan pajak panjang. Unit repossess siap pakai untuk usaha angkutan barang maupun logistik harian.",
  },
  {
    id: "koelak-004",
    nama: "200 Buah Kursi Plastik Stacking Outdoor",
    kategori: "Furnitur",
    harga_lelang: 6000000,
    harga_pasaran: 6300000,
    diskon_persen: 4.8,
    tier: "D",
    lokasi: "Medan",
    kpknl: "",
    deadline: deadlineIn(6),
    link: "https://lelang.beacukai.go.id/lot/koelak-004",
    foto: "[]",
    sumber: "KOELAK",
    uang_jaminan: null,
    deskripsi:
      "Dua ratus kursi plastik stacking bekas event pemerintah, sebagian kusam dan kotor namun tidak patah. Diskon sangat tipis terhadap harga pasaran, hanya layak bila butuh jumlah banyak sekaligus.",
  },
  {
    id: "djkn-efg123",
    nama: "Gitar Akustik Yamaha FG800 + Amplifier 15W",
    kategori: "Hobi",
    harga_lelang: 1400000,
    harga_pasaran: 2600000,
    diskon_persen: 46.2,
    tier: "B",
    lokasi: "Malang",
    kpknl: "KPKNL Malang",
    deadline: deadlineIn(7),
    link: "https://lelang.go.id/lot-lelang/djkn-efg123",
    foto: fotoSet("efg123", 2),
    sumber: "DJKN",
    uang_jaminan: 280000,
    deskripsi:
      "Gitar akustik Yamaha FG800 spruce top dengan amplifier 15W bergain. Fretboard mulus, action nyaman, suara full dan dalam khas FG series. Cocok untuk pemula sampai menengah yang cari bundle hemat.",
  },
  {
    id: "ibid-777",
    nama: "Kamera Canon EOS 700D + Lensa Kit 18-55mm",
    kategori: "Hobi",
    harga_lelang: 4300000,
    harga_pasaran: 6500000,
    diskon_persen: 33.8,
    tier: "B",
    lokasi: "Jakarta Selatan",
    kpknl: "",
    deadline: deadlineIn(4),
    link: "https://www.ibid.astra.id/lot/ibid-777",
    foto: fotoSet("ibid777", 3),
    sumber: "IBID",
    uang_jaminan: 860000,
    deskripsi:
      "Canon EOS 700D shutter count 21.000 dengan lensa kit 18-55mm IS. Sensor bersih, layar flip articulta normal, termasuk charger dan baterai 2 buah. Kamera entry level legendaris untuk belajar fotografi serius.",
  },
  {
    id: "djkn-hij456",
    nama: "1 Unit Tablet Samsung Galaxy Tab S9 128GB WiFi",
    kategori: "Elektronik",
    harga_lelang: 6800000,
    harga_pasaran: 11999000,
    diskon_persen: 43.3,
    tier: "B",
    lokasi: "Tangerang",
    kpknl: "KPKNL Tangerang",
    deadline: deadlineIn(2),
    link: "https://lelang.go.id/lot-lelang/djkn-hij456",
    foto: fotoSet("hij456", 3),
    sumber: "DJKN",
    uang_jaminan: 1360000,
    deskripsi:
      "Samsung Galaxy Tab S9 128GB WiFi berwarna Graphite, layar AMOLED 11 inci 120Hz, include S Pen. Kondisi mulus 97%, baterai sehat, tanpa minus. Unit eks inventaris kantor dengan kelengkapan box dan charger original.",
  },
  {
    id: "koelak-005",
    nama: "1 Unit Mesin Fotokopi Multifungsi A3 Ricoh",
    kategori: "Elektronik",
    harga_lelang: 7500000,
    harga_pasaran: 26000000,
    diskon_persen: 71.2,
    tier: "S",
    lokasi: "Jakarta Selatan",
    kpknl: "",
    deadline: deadlineIn(9),
    link: "https://lelang.beacukai.go.id/lot/koelak-005",
    foto: fotoSet("koelak005", 3),
    sumber: "KOELAK",
    uang_jaminan: 1500000,
    deskripsi:
      "Mesin fotokopi multifungsi Ricoh Aficio A3 print-copy-scan, counter rendah 180 ribu, hasil cetak tajam.SUPER DEAL untuk usaha jasa fotokopi atau kantor yang butuh mesin tahan banting. Termasuk standing table besi.",
  },
  {
    id: "ibid-778",
    nama: "Xiaomi Redmi Note 12 8/256GB Baru Sein",
    kategori: "Elektronik",
    harga_lelang: 1750000,
    harga_pasaran: 2499000,
    diskon_persen: 30.0,
    tier: "B",
    lokasi: "Surabaya",
    kpknl: "",
    deadline: "",
    link: "https://www.ibid.astra.id/lot/ibid-778",
    foto: fotoSet("ibid778", 2),
    sumber: "IBID",
    uang_jaminan: 350000,
    deskripsi:
      "Xiaomi Redmi Note 12 8/256GB baru segel resmi SEIN garansi distributor 1 tahun. Lelang tanpa batas waktu hingga penawar tertentu tercapai, deadline mengikuti pengumuman lelang. Warna Onyx Gray.",
  },
  {
    id: "djkn-klm789",
    nama: "1 Buah Laptop Acer Aspire 3 A315 Core i3",
    kategori: "Elektronik",
    harga_lelang: 3900000,
    harga_pasaran: null,
    diskon_persen: null,
    tier: null,
    lokasi: "Bandung",
    kpknl: "KPKNL Bandung",
    deadline: deadlineIn(8),
    link: "https://lelang.go.id/lot-lelang/djkn-klm789",
    foto: fotoSet("klm789", 2),
    sumber: "DJKN",
    uang_jaminan: 780000,
    deskripsi:
      "Laptop Acer Aspire 3 A315 Core i3 generasi 11, RAM 8GB, SSD 512GB. Kondisi normal menyala, bodi rapi. Harga pasaran belum dinilai oleh tim penilai sehingga tier diskon belum dapat dihitung untuk lot ini.",
  },
  {
    id: "djkn-nop012",
    nama: "Sepeda Listrik Nikita ES2 Range 40km",
    kategori: "Hobi",
    harga_lelang: 5600000,
    harga_pasaran: 6000000,
    diskon_persen: 6.7,
    tier: "D",
    lokasi: "Bogor",
    kpknl: "KPKNL Bogor",
    deadline: deadlineIn(3),
    link: "https://lelang.go.id/lot-lelang/djkn-nop012",
    foto: fotoSet("nop012", 2),
    sumber: "DJKN",
    uang_jaminan: 1120000,
    deskripsi:
      "Sepeda listrik Nikita ES2 battery 48V range 40 km, kondisi battery masih sehat dan motor penggerak normal. Harga lelang tipis terhadap pasaran sehingga masuk kategori SKIP bagi pembeli investasi, tapi tetap layak bagi yang memang butuh.",
  },
];
